<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class PuntoDelictivoImageRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            "id_punto_delictivo" => ["required", Rule::exists('puntos_delictivo', 'id')],
            "imagen" => ["required", "image", "mimes:jpg,png,jpeg"],
        ];
    }

    protected function failedValidation(Validator $validator)
    {
        $msg = 'registrarImagenPunto';
        $response = redirect()
            ->back()
            ->with($msg, $msg)
            ->withErrors($validator);
        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
